Changed the classpath search to use our own version of the postgresql.jar first, otherwise search for an installed version. Tackles the issue of outdated postgres jars.

diff --git a/bin/akdump b/bin/akdump
--- a/bin/akdump
+++ b/bin/akdump
@@ -1,6 +1,13 @@
 #!/bin/bash
-JAR=$(ls $(dirname $0)/../target/akiban-client-tools-*.*.*-SNAPSHOT.jar)
-if [ -z "$JAR" ]; then
-  JAR=/usr/share/akiban/akiban-client-tools.jar
+
+
+if [ -f "$(dirname $0)/../pom.xml" ]; then
+    JAR=$(ls $(dirname $0)/../target/akiban-client-tools-*.*.*-SNAPSHOT.jar)
+else
+    JAR=/usr/share/akiban/akiban-client-tools.jar
 fi
-java -cp /usr/share/java/postgresql-jdbc3.jar:$JAR com.akiban.client.dump.DumpClient "$@"
+
+[ -z "$JAR" ] && { echo "$0: Error: Couldn't find akiban-client-tools.jar in /usr/share/akiban/"; exit 1; }
+
+classpath="/usr/share/akiban/postgresql.jar:/usr/share/java/postgresql-jdbc3.jar:${JAR}"
+java -cp ${classpath} com.akiban.client.dump.DumpClient "$@"
